export const UPDATE_SERIES = 'UPDATE_SERIES';
export const QUERY_SERIES = 'QUERY_SERIES';
export const UPDATE_EPISODE_STATUS = 'UPDATE_EPISODE_STATUS';
export const UPDATE_SEASON_STATUS = 'UPDATE_SEASON_STATUS';
export const ADD_EPISODE = 'ADD_EPISODE';
export const ADD_SEASON = 'ADD_SEASON';
